- platform: mqtt
  state_topic: "cmnd/motion_front/POWER1"
  name: "Teras"
  device_class: motion
  qos: 0
  payload_on: "ON"
  payload_off: "OFF"
- platform: mqtt
  state_topic: "cmnd/motion_back/POWER1"
  name: "Ruang Cuci"
  device_class: motion
  qos: 0
  payload_on: "ON"
  payload_off: "OFF"
- platform: mqtt
  state_topic: "NodeMCU1/Motion1/Status"
  name: "Ruang Tamu"
  device_class: motion
  qos: 0
  payload_on: "1"
  payload_off: "0"
- platform: mqtt
  state_topic: "NodeMCU2/Radar1/Status"
  name: "Dapur"
  device_class: motion
  qos: 0
  payload_on: "1"
  payload_off: "0"
- platform: mqtt
  state_topic: "NodeMCU1/Door1/Status"
  name: "Pintu Utama"
  device_class: opening
  qos: 0
  payload_on: "1"
  payload_off: "0"
- platform: mqtt
  state_topic: "NodeMCU1/Door2/Status"
  name: "Pintu Dapur"
  device_class: opening
  qos: 0
  payload_on: "1"
  payload_off: "0"
- platform: mqtt
  state_topic: "NodeMCU1/Door3/Status"
  name: "Pintu Ruang Makan"
  device_class: opening
  qos: 0
  payload_on: "1"
  payload_off: "0"  
# yg di bawah buat floorplan
- platform: mqtt
  state_topic: dummy/floorplan/sensor
  name: Floorplan
