default_view:
  view: true
  icon: mdi:home
  entities:
  - group.awesome_people
  - group.external_lights
  - group.motion_detectors
  - group.openings
  - group.environment
  - media_player.ruang_tv
climate:
  view: true
  icon: mdi:thermometer
  entities:
  # - group.daily_forecast
  # - group.weather_overview
  - group.dark_sky
automation:
  name: Automation
  icon: mdi:flash-auto
  view: true
  entities:
  - automation.update_available_notifications
  - automation.ping_pong_bot
  - automation.turn_on_light_when_sun_sets
  - automation.turn_off_light_when_sun_rises
  - automation.SunElevationDark
resource:
  name: Resource
  icon: mdi:desktop-tower
  view: true
  entities:
  - group.server
server:
  name: Server Utilization
  icon: mdi:laptop-mac
  view: false
  entities:
  - sensor.cpu_use
  - sensor.ram_free
  - sensor.disk_use
  - sensor.average_load_1m
  - sensor.average_load_5m
  - sensor.average_load_15m
  - sensor.last_boot
awesome_people:
  name: 36ers
  view: false
  entities:
  - device_tracker.90187c1b4a88
  - sensor.rpm
  - device_tracker.34a395c33c50
  - device_tracker.205ef7734ec8
  - device_tracker.00376de2226f
external_lights:
  name: External Lights
  view: false
  entities:
  - light.lampu_luar_belakang
  - light.lampu_luar_depan
motion_detectors:
  name: Motion Detectors
  view: false
  entities:
  - binary_sensor.teras
  - binary_sensor.ruang_tamu

openings:
  name: Doors and Windows
  view: false
  entities:
  - binary_sensor.pintu_utama
  - binary_sensor.pintu_dapur
  - binary_sensor.pintu_ruang_makan

environment:
  name: Home Environment
  icon: mdi:home-variant
  view: false
  entities:
  - sensor.date__time
  - sun.sun
  - sensor.moon
  - sensor.temperature
  - sensor.humidity
# daily_forecast:
#   name: Daily Forecast
#   view: false
#   entities:
#   - sensor.pws_weather_1d_metric
#   - sensor.pws_weather_1n_metric
#   - sensor.pws_weather_2d_metric
#   - sensor.pws_weather_2n_metric
#   - sensor.pws_weather_3d_metric
#   - sensor.pws_weather_3n_metric
#   - sensor.pws_weather_4d_metric
#   - sensor.pws_weather_4n_metric
# weather_overview:
#   name: Weather overview
#   view: false
#   entities:
#   - sensor.pws_weather_1d_metric
#   - sensor.pws_feelslike_c
#   - sensor.pws_temp_high_1d_c
#   - sensor.pws_temp_c
#   - sensor.pws_temp_low_1d_c
#   - sensor.pws_heat_index_c
#   - sensor.pws_solarradiation
#   - sensor.pws_UV
#   - sensor.pws_relative_humidity
#   - sensor.pws_pressure_mb
#   - sensor.pws_precip_today_metric
#   - sensor.pws_precip_1d_mm
#   - sensor.pws_wind_gust_kph
#   - sensor.pws_wind_gust_1d_kph
#   - sensor.pws_visibility_km
#   - sensor.pws_alerts
#   - sensor.pws_observation_time
dark_sky:
  name: Dark Sky
  view: false
  entities:
  - sun.sun
  - sensor.moon
  - sensor.dark_sky_daily_summary
  - sensor.dark_sky_temperature
  - sensor.dark_sky_apparent_temperature
  - sensor.dark_sky_humidity
  - sensor.dark_sky_pressure
  - sensor.dark_sky_ozone
  - sensor.dark_sky_wind_speed
  - sensor.dark_sky_wind_bearing

