- platform: mqtt
  name: "Lampu Luar Belakang"
  state_topic: "stat/sw_ext_back/POWER"
  command_topic: "cmnd/sw_ext_back/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  qos: 1
  retain: true
- platform: mqtt
  name: "Lampu Luar Depan"
  state_topic: "stat/sw_ext_front/POWER"
  command_topic: "cmnd/sw_ext_front/POWER"
  payload_on: "ON"
  payload_off: "OFF"
  qos: 1
  retain: true