- platform: moon
- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
- platform: systemmonitor
  resources:
    - type: processor_use
    - type: memory_free
    - type: disk_use_percent
      arg: /
    - type: load_1m
    - type: load_5m
    - type: load_15m
    - type: last_boot
- platform: google_geocode
  name: RPM
  origin: device_tracker.nyamuk_rpmedge
  options: street, city
  # display_zone: hide
- platform: mqtt
  name: "Suhu Ruang TV"
  state_topic: "NodeMCU1/SuhuInt/Temperature"
  qos: 0
  unit_of_measurement: "ºC"
- platform: mqtt
  name: "Suhu Dapur"
  state_topic: "tele/sw_dapur/SENSOR"
  value_template: "{{ value_json.DS18B20.Temperature }}"
  qos: 0
  unit_of_measurement: "ºC"
- platform: mqtt
  name: "Humidity"
  state_topic: "NodeMCU1/SuhuInt/Humidity"
  qos: 0
  unit_of_measurement: "%"
- platform: mqtt
  name: "Ambient Light"
  state_topic: "NodeMCU1/AmbientLight/Lux"
  qos: 0
  unit_of_measurement: "Lux"
- platform: template
  sensors:
    template_last_motion:
      friendly_name: 'Last Motion'
      value_template: >
        {%- set sensors = [states.binary_sensor.ruang_makan,states.binary_sensor.dapur,states.binary_sensor.ruang_cuci, states.binary_sensor.teras, states.binary_sensor.ruang_tamu, states.binary_sensor.pintu_utama, states.binary_sensor.pintu_dapur, states.binary_sensor.pintu_ruang_makan] %}
        {% for sensor in sensors %}
          {% if as_timestamp(sensor.last_changed) == as_timestamp(sensors | map(attribute='last_changed') | max) %}
            {{ sensor.name }}
          {% endif %}
        {% endfor %}
#
#
#  Almanac Sensors
#
#
- platform: template
  sensors:
    floorplan_date:
      friendly_name: 'Formatted Date'
      value_template: "{{now().strftime('%A, %d %b %Y') }}"
      # nextsunrise:
       # friendly_name: 'Next Sunrise'
       # value_template: "{{ as_timestamp(states.sun.sun.attributes.next_rising) | timestamp_custom('%D %-I:%M %P') }}"

     # nextsunset:
       # friendly_name: 'Next Sunset'
       # value_template: "{{ as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom('%D %-I:%M %P') }}"
       
     # dayofyear:
       # friendly_name: 'Day Number'
       # value_template: "{{ now().strftime('%j') }}"


# - platform: wunderground
#   api_key: !secret wu_api_key
#   monitored_conditions:
#     # - alerts
#     - feelslike_c
#     - heat_index_c
#     - observation_time
#     - precip_1d_mm
#     - precip_today_metric
#     - pressure_mb
#     - relative_humidity
#     - solarradiation
#     - temp_c
#     # - temp_high_1d_c
#     # - temp_low_1d_c
#     - UV
#     - visibility_km
#     - weather
#     - wind_dir
#     - wind_gust_kph
#     # - wind_gust_1d_kph
#     - weather_1d_metric
#     - weather_1n_metric
#     # - weather_2d_metric
    # - weather_2n_metric
    # - weather_3d_metric
    # - weather_3n_metric
    # - weather_4d_metric
    # - weather_4n_metric
- platform: darksky
  api_key: !secret darksky_api_key
  monitored_conditions:
    - summary
    - icon
    - temperature
    - apparent_temperature
    - temperature_min
    - temperature_max
    - humidity
    - pressure
    - visibility
    - wind_speed
    - wind_bearing
    - cloud_cover
    - ozone
    - daily_summary
# - platform: yweather
#   monitored_conditions:
#     - weather
#     - weather_current
#     - temp_min
#     - temp_max
#     - wind_speed
#     - pressure
#     - visibility
#     - humidity
#     - temperature
